/**
 * Mapeamento central obrigatório das linhas DRE.
 * Evita dupla contagem e mantém fórmula/fonte explícitas.
 */

import type { DreLineCode, DreLineMapping } from './dre-lines.types';

export const DRE_LINE_MAPPINGS: DreLineMapping[] = [
  {
    line_code: 'faturamento_bruto',
    line_label: 'Faturamento bruto',
    line_group: 'receita',
    sort_order: 1,
    indent_level: 0,
    is_group: true,
    is_subline: false,
    sign_type: 'positive',
    formula: 'totals.totalCliente || quotes.value',
    presumed_source: 'quotes.pricing_breakdown.totals.totalCliente | quotes.value',
    real_source: 'orders.value',
  },
  {
    line_code: 'impostos',
    line_label: 'Impostos',
    line_group: 'impostos',
    sort_order: 2,
    indent_level: 0,
    is_group: true,
    is_subline: false,
    sign_type: 'negative',
    formula: 'das + icms',
    presumed_source: 'quotes.pricing_breakdown.totals.{das,icms}',
    real_source: 'stored taxes or calc from fiscal rates',
  },
  {
    line_code: 'das',
    line_label: 'DAS',
    line_group: 'impostos',
    sort_order: 3,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'tax amount',
    presumed_source: 'quotes.pricing_breakdown.totals.das',
    real_source: 'orders stored tax or rates.dasPercent',
  },
  {
    line_code: 'icms',
    line_label: 'ICMS',
    line_group: 'impostos',
    sort_order: 4,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'tax amount',
    presumed_source: 'quotes.pricing_breakdown.totals.icms',
    real_source: 'orders stored tax or rates.icmsPercent',
  },
  {
    line_code: 'receita_liquida',
    line_label: 'Receita líquida',
    line_group: 'receita',
    sort_order: 5,
    indent_level: 0,
    is_group: true,
    is_subline: false,
    sign_type: 'positive',
    formula: 'faturamento_bruto - das - icms',
    presumed_source: 'derived',
    real_source: 'derived',
  },
  {
    line_code: 'overhead',
    line_label: 'Overhead',
    line_group: 'custos',
    sort_order: 6,
    indent_level: 0,
    is_group: true,
    is_subline: false,
    sign_type: 'negative',
    formula: 'receita_liquida * overhead_rate',
    presumed_source: 'quotes.pricing_breakdown.profitability.overhead',
    real_source: 'quote overhead percent over real receita líquida',
  },
  {
    line_code: 'custos_diretos',
    line_label: 'Custos diretos',
    line_group: 'custos',
    sort_order: 7,
    indent_level: 0,
    is_group: true,
    is_subline: false,
    sign_type: 'negative',
    formula:
      'custo_motorista + pedagio + carga_descarga + espera + taxas_condicionais + outros_custos',
    presumed_source: 'sum of atomic presumed lines',
    real_source: 'sum of atomic real lines',
  },
  {
    line_code: 'custo_motorista',
    line_label: 'Custo motorista / carreteiro',
    line_group: 'custos',
    sort_order: 8,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'carreteiro amount',
    presumed_source: 'quotes.pricing_breakdown.profitability.{custoMotorista|custosCarreteiro}',
    real_source: 'orders.carreteiro_real',
  },
  {
    line_code: 'pedagio',
    line_label: 'Pedágio',
    line_group: 'custos',
    sort_order: 9,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'pedágio amount',
    presumed_source: 'quotes.pricing_breakdown.components.toll',
    real_source: 'orders.pedagio_real',
  },
  {
    line_code: 'carga_descarga',
    line_label: 'Carga e descarga',
    line_group: 'custos',
    sort_order: 10,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'descarga amount',
    presumed_source: 'quotes.pricing_breakdown.profitability.custosDescarga',
    real_source: 'orders.descarga_real',
  },
  {
    line_code: 'espera',
    line_label: 'Espera',
    line_group: 'custos',
    sort_order: 11,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'waiting_time_cost',
    presumed_source: 'quotes.pricing_breakdown.components.waitingTimeCost',
    real_source: 'orders.waiting_time_cost',
  },
  {
    line_code: 'taxas_condicionais',
    line_label: 'Taxas condicionais',
    line_group: 'custos',
    sort_order: 12,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'conditional fees sum',
    presumed_source: 'quotes.pricing_breakdown.components.conditionalFeesTotal',
    real_source: 'trip_cost_items (scope=OS, conditional categories)',
  },
  {
    line_code: 'outros_custos',
    line_label: 'Outros custos operacionais',
    line_group: 'custos',
    sort_order: 13,
    indent_level: 1,
    is_group: false,
    is_subline: true,
    sign_type: 'negative',
    formula: 'misc sum',
    presumed_source: 'quotes breakdown extra components (e.g. aluguel/risk/service)',
    real_source: 'order_gris_services.amount_real + risk_costs + trip_cost_items misc',
  },
  {
    line_code: 'resultado_liquido',
    line_label: 'Resultado líquido',
    line_group: 'resultado',
    sort_order: 14,
    indent_level: 0,
    is_group: true,
    is_subline: false,
    sign_type: 'positive',
    formula: 'receita_liquida - overhead - custos_diretos',
    presumed_source: 'derived (never primary from JSON aggregate)',
    real_source: 'derived',
  },
  {
    line_code: 'margem_liquida',
    line_label: 'Margem líquida',
    line_group: 'resultado',
    sort_order: 15,
    indent_level: 0,
    is_group: true,
    is_subline: false,
    sign_type: 'positive',
    formula: 'resultado_liquido / faturamento_bruto',
    presumed_source: 'derived',
    real_source: 'derived',
  },
];

export const DRE_LINE_MAP = new Map<DreLineCode, DreLineMapping>(
  DRE_LINE_MAPPINGS.map((item) => [item.line_code, item])
);

export function getDreLineMapping(code: DreLineCode): DreLineMapping | undefined {
  return DRE_LINE_MAP.get(code);
}

export function isPositiveLine(code: DreLineCode): boolean {
  return getDreLineMapping(code)?.sign_type === 'positive';
}
